name: Tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    name: Run tests
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v8
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install dependencies
        run: poetry install
      - name: Test with pytest
        run: poetry run pytest --cov gnukek_cli/
